import logging
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from koinapy import Koina

from optimhc import utils
from optimhc.feature.base_feature_generator import BaseFeatureGenerator
from optimhc.feature.factory import feature_generator_factory
from optimhc.feature.numba_utils import align_peaks, compute_similarity_features
from optimhc.parser import extract_mzml_data
from optimhc.peptidoform import to_proforma

logger = logging.getLogger(__name__)


class SpectralSimilarityFeatureGenerator(BaseFeatureGenerator):
    """
    Feature generator for calculating similarity between experimental and predicted spectra.

    This class works through the following steps:
    1. Extract experimental spectral data from mzML files
    2. Use Koina for theoretical spectra prediction
    3. Align experimental and predicted spectra
    4. Calculate similarity metrics as features

    Parameters
    ----------
    peptides : list of str
        List of peptide sequences.
    charges : list of int
        List of charge states.
    scan_ids : list of int
        List of scan IDs.
    mz_file_paths : list of str
        List of mzML file paths.
    model_type : str
        Prediction model type, either "HCD" or "CID".
    collision_energies : list of float
        List of collision energies, required when model_type is "HCD".
    remove_pre_nxt_aa : bool
        Whether to remove flanking previous/next amino acids from peptide sequences.
        Default is False.
    mod_dict : dict, optional
        Literal text replacements applied to peptide strings before prediction.
    url : str
        Koina server URL, default is "koina.wilhelmlab.org:443".
    top_n : int
        Number of top peaks to use for alignment, default is 12.
    tolerance_ppm : float
        Mass tolerance for alignment in ppm, default is 20.
    """

    def __init__(
        self,
        spectrum_ids: List[str],
        peptides: List[str],
        charges: List[int],
        scan_ids: List[int],
        mz_file_paths: List[str],
        model_type: str,
        collision_energies: List[float] = None,
        instruments: List[str] = None,
        fragmentation_types: List[str] = None,
        remove_pre_nxt_aa: bool = False,
        mod_dict: Optional[Dict[str, str]] = None,
        url: str = "koina.wilhelmlab.org:443",
        ssl: bool = True,
        top_n: int = 36,
        tolerance_ppm: float = 20,
    ):
        self.spectrum_ids = spectrum_ids
        self.peptides = peptides
        self.charges = charges
        self.scan_ids = scan_ids
        self.mz_file_paths = mz_file_paths
        self.model_type = model_type
        self.collision_energies = collision_energies
        self.instruments = instruments
        self.fragmentation_types = fragmentation_types
        self.remove_pre_nxt_aa = remove_pre_nxt_aa
        self.mod_dict = mod_dict
        self.url = url
        self.ssl = ssl
        self.top_n = top_n
        self.tolerance_ppm = tolerance_ppm
        self.results = None
        self._raw_predictions = None

        logger.info(f"Initializing SpectralSimilarityFeatureGenerator with {len(peptides)} PSMs")
        logger.info(f"Using model: {self.model_type}")

        self.df = pd.DataFrame(
            {
                "spectrum_id": self.spectrum_ids,
                "scan": self.scan_ids,
                "peptide": self.peptides,
                "charge": self.charges,
                "mz_file_path": self.mz_file_paths,
            }
        )

        self.df["processed_peptide"] = self.df["peptide"].apply(self._preprocess_peptide)
        logger.info(f"Received {len(self.df)} PSMs for spectral similarity feature generation")

    @property
    def id_column(self) -> List[str]:
        """
        Returns a list of input columns required for the feature generator.
        """
        return ["spectrum_id", "peptide", "charge"]

    @property
    def feature_columns(self) -> List[str]:
        """
        Returns a list of feature columns generated by the feature generator.
        """
        return [
            "spectral_angle_similarity",
            "cosine_similarity",
            "pearson_correlation",
            "spearman_correlation",
            "mean_squared_error",
            "unweighted_entropy_similarity",
            "predicted_seen_nonzero",
            "predicted_not_seen",
        ]

    def input_df(self) -> pd.DataFrame:
        """
        Return the generated features as a DataFrame.

        Returns
        -------
        pd.DataFrame
            DataFrame containing the generated features.
        """
        return self.df

    def _preprocess_peptide(self, peptide: str) -> str:
        """
        Preprocess peptide sequence.

        As Prosit does not support non-standard amino acid 'U', we replace it with 'C'.

        Parameters
        ----------
        peptide : str
            Original peptide sequence.

        Returns
        -------
        str
            Processed peptide sequence.

        Notes
        -----
        This is nonsense when it comes to spectral prediction, but we need to keep it
        for compatibility with Koina. In the future, this should be prohibited at the input level.
        """
        processed_peptide = peptide

        if self.remove_pre_nxt_aa:
            processed_peptide = utils.strip_flanking_and_charge(processed_peptide)

        if self.mod_dict is not None:
            for mod, replacement in self.mod_dict.items():
                processed_peptide = processed_peptide.replace(mod, replacement)

        # Replace non-standard amino acid 'U' with 'C'.
        # This is nosense when it comes to spectral prediction.
        # But we need to keep it for compatibility with Koina.
        # In the future, this should be prohibited at the input level.
        if "U" in utils.remove_modifications(processed_peptide):
            logger.warning(
                f"Peptide sequence contains non-standard amino acid 'U': {processed_peptide}. Replacing with 'C'."
            )
            # Replace 'U' with 'C'
            processed_peptide = processed_peptide.replace("U", "C")

        return processed_peptide

    def _extract_experimental_spectra(self) -> pd.DataFrame:
        """
        Extract experimental spectral data from mzML files.

        Returns
        -------
        pd.DataFrame
            DataFrame containing experimental spectral data.

        Notes
        -----
        The method groups scan IDs by file path for efficiency and extracts
        spectral data from each mzML file. The resulting DataFrame contains
        m/z values, intensities, and associated metadata for each spectrum.
        """
        logger.info("Extracting experimental spectral data...")

        # Group scan IDs by file path for efficiency
        file_to_scans = {}
        for i, row in self.df.iterrows():
            scan_id = row["scan"]
            file_path = row["mz_file_path"]
            if file_path not in file_to_scans:
                file_to_scans[file_path] = []
            file_to_scans[file_path].append(scan_id)

        exp_spectra_dfs = []
        for file_path, scan_ids in file_to_scans.items():
            logger.info(f"Extracting {len(scan_ids)} scans from {file_path}")
            spectra_df = extract_mzml_data(file_path, scan_ids)
            spectra_df["mz_file_path"] = file_path
            exp_spectra_dfs.append(spectra_df)

        # Merge spectral data from all files
        if exp_spectra_dfs:
            exp_spectra_df = pd.concat(exp_spectra_dfs, ignore_index=True)
            logger.info(f"Successfully extracted {len(exp_spectra_df)} experimental spectra")
            return exp_spectra_df
        else:
            logger.warning("No experimental spectral data found")
            return pd.DataFrame()

    def _predict_theoretical_spectra(
        self, processed_peptides: List[str], charges: List[int]
    ) -> pd.DataFrame:
        """
        Use Koina to predict theoretical spectra.

        Parameters
        ----------
        processed_peptides : list of str
            List of preprocessed peptide sequences.
        charges : list of int
            List of charge states.

        Returns
        -------
        pd.DataFrame
            DataFrame containing predicted spectral data.

        Raises
        ------
        Exception
            If there is an error during Koina prediction.

        Notes
        -----
        The method uses Koina to predict theoretical spectra for each peptide.
        For AlphaPeptDeep_ms2_generic model, inputs are split into batches
        grouped by peptide length for prediction.
        """
        logger.info(f"Predicting theoretical spectra using {self.model_type}...")

        inputs = pd.DataFrame()
        inputs["peptide_sequences"] = np.array(processed_peptides)
        inputs["precursor_charges"] = np.array(charges)

        if self.collision_energies is not None:
            inputs["collision_energies"] = np.array(self.collision_energies)

        if self.instruments is not None:
            inputs["instrument_types"] = np.array(self.instruments)

        if self.fragmentation_types is not None:
            inputs["fragmentation_types"] = np.array(self.fragmentation_types)

        model = Koina(self.model_type, self.url, ssl=self.ssl)

        try:
            predictions = model.predict(inputs)
        except Exception as e:
            logger.error(f"Error during Koina prediction: {e}")
            logger.error("Koina prediction failed. Please check:")
            logger.error("- Input parameters compatibility")
            logger.error("- Supported modifications")
            logger.error("- Peptide length limits")
            logger.error("Details at: https://koina.proteomicsdb.org/")

            if self.model_type == "AlphaPeptDeep_ms2_generic":
                logger.info(
                    "Splitting inputs into batches grouped by peptide length for prediction..."
                )
                import re

                # Compute peptide length by removing modifications in square brackets.
                inputs["peptide_length"] = inputs["peptide_sequences"].apply(
                    lambda x: len(re.sub(r"\[.*?\]", "", x))
                )

                predictions_batches = []
                # Group the DataFrame by calculated peptide length. Each group is submitted as one batch.
                for peptide_length, group in inputs.groupby("peptide_length"):
                    logger.info(
                        f"Processing {len(group)} entries for peptide length {peptide_length}."
                    )
                    try:
                        batch_predictions = model.predict(group)
                        predictions_batches.append(batch_predictions)
                    except Exception as batch_error:
                        logger.error(
                            f"Error during Koina prediction for batch with peptide length {peptide_length}: {batch_error}"
                        )
                        logger.error(f"Batch data:\n{group}")
                        # # Save the batch data for debugging
                        # group.to_csv(
                        #     f"batch_error_peptide_length_{peptide_length}.csv",
                        #     index=False,
                        # )
                        # logger.error(
                        #     f"Batch data saved to batch_error_peptide_length_{peptide_length}.csv"
                        # )
                        raise
                predictions = pd.concat(predictions_batches, ignore_index=True)
            else:
                raise ValueError(f"Unsupported model type: {self.model_type}")

        # Save the raw prediction results
        self._raw_predictions = predictions.copy()

        # Convert prediction results to a suitable format
        pred_df = predictions.copy()
        pred_df.rename(
            columns={
                "peptide_sequences": "processed_peptide",
                "precursor_charges": "charge",
                "intensities": "pred_intensity",
                "mz": "pred_mz",
            },
            inplace=True,
        )

        # Group by peptide and charge, convert predicted mz and intensity to lists
        grouped_df = (
            pred_df.groupby(["processed_peptide", "charge"])
            .agg({"pred_intensity": list, "pred_mz": list, "annotation": list})
            .reset_index()
        )

        logger.info(f"Successfully predicted {len(grouped_df)} theoretical spectra")
        return grouped_df

    @property
    def raw_predictions(self) -> pd.DataFrame:
        """
        Returns the raw prediction results from Koina.

        Returns
        -------
        pd.DataFrame
            Raw prediction results DataFrame.
        """
        if self._raw_predictions is None:
            if self.results is None:
                self.results = self._generate_features()
        return self._raw_predictions

    def get_raw_predictions(self) -> pd.DataFrame:
        """
        Get the raw prediction results DataFrame from Koina.

        Returns
        -------
        pd.DataFrame
            Raw prediction results DataFrame.
        """
        return self.raw_predictions

    def save_raw_predictions(self, file_path: str, **kwargs) -> None:
        """
        Save the raw prediction results to a file.

        Parameters
        ----------
        file_path : str
            Path to save the file.
        **kwargs
            Other parameters passed to ``pandas.DataFrame.to_csv``.
        """
        if "index" not in kwargs:
            kwargs["index"] = False
        if self.raw_predictions is not None:
            self.raw_predictions.to_csv(file_path, **kwargs)
            logger.info(f"Raw prediction results saved to: {file_path}")
        else:
            logger.warning("No raw prediction results available to save.")

    def _sort_spectrum_by_mz(
        self,
        mz: List[float],
        intensity: List[float],
        annotation: Optional[List[str]] = None,
    ) -> Tuple[np.ndarray, np.ndarray, Optional[np.ndarray]]:
        """
        Sort spectrum (m/z, intensity, and optionally annotation) by m/z values.

        Parameters
        ----------
        mz : list of float
            m/z values.
        intensity : list of float
            Intensity values.
        annotation : list of str, optional
            Fragment annotations.

        Returns
        -------
        tuple of (np.ndarray, np.ndarray, np.ndarray or None)
            Sorted m/z, intensity, and annotation arrays.
            If annotation is None, the third element will be None.
        """
        mz_array = np.array(mz)
        intensity_array = np.array(intensity)
        sorted_indices = np.argsort(mz_array)
        sorted_mz = mz_array[sorted_indices]
        sorted_intensity = intensity_array[sorted_indices]

        sorted_annotation = None
        if annotation is not None:
            annotation_array = np.array(annotation)
            sorted_annotation = annotation_array[sorted_indices]

        return sorted_mz, sorted_intensity, sorted_annotation

    def _align_spectra_all_peaks(
        self,
        exp_mz: List[float],
        exp_intensity: List[float],
        pred_mz: List[float],
        pred_intensity: List[float],
        pred_annotation: Optional[List[str]] = None,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray, Dict]:
        """
        Align experimental and predicted spectra using ppm tolerance.

        Parameters
        ----------
        exp_mz : list of float
            Experimental m/z values.
        exp_intensity : list of float
            Experimental intensity values.
        pred_mz : list of float
            Predicted m/z values.
        pred_intensity : list of float
            Predicted intensity values.
        pred_annotation : list of str, optional
            Predicted fragment annotations.

        Returns
        -------
        tuple of (np.ndarray, np.ndarray, np.ndarray, dict)
            - Aligned experimental intensity vector
            - Predicted intensity vector
            - Matching index pairs as int array of shape (N, 2),
              where column 0 is pred_idx and column 1 is exp_idx (-1 = no match)
            - Additional info including original sorted arrays
        """
        # Sort both experimental and predicted spectra by m/z
        exp_mz_sorted, exp_intensity_sorted, _ = self._sort_spectrum_by_mz(exp_mz, exp_intensity)

        if pred_annotation is not None:
            pred_mz_sorted, pred_intensity_sorted, pred_annotation_sorted = (
                self._sort_spectrum_by_mz(pred_mz, pred_intensity, pred_annotation)
            )
        else:
            pred_mz_sorted, pred_intensity_sorted, pred_annotation_sorted = (
                self._sort_spectrum_by_mz(pred_mz, pred_intensity)
            )

        n_pred = len(pred_mz_sorted)
        aligned_pred_intensity = pred_intensity_sorted.copy()

        aligned_exp_intensity, matched_exp_indices = align_peaks(
            np.ascontiguousarray(exp_mz_sorted, dtype=np.float64),
            np.ascontiguousarray(exp_intensity_sorted, dtype=np.float64),
            np.ascontiguousarray(pred_mz_sorted, dtype=np.float64),
            self.tolerance_ppm,
        )

        matched_indices = np.empty((n_pred, 2), dtype=np.int64)
        matched_indices[:, 0] = np.arange(n_pred)
        matched_indices[:, 1] = matched_exp_indices

        additional_info = {
            "exp_mz_sorted": exp_mz_sorted,
            "exp_intensity_sorted": exp_intensity_sorted,
            "pred_mz_sorted": pred_mz_sorted,
            "pred_intensity_sorted": pred_intensity_sorted,
            "pred_annotation_sorted": pred_annotation_sorted,
        }

        return (
            aligned_exp_intensity,
            aligned_pred_intensity,
            matched_indices,
            additional_info,
        )

    def _get_top_peaks_vectors(
        self,
        aligned_exp_intensity: np.ndarray,
        aligned_pred_intensity: np.ndarray,
        matched_indices: np.ndarray,
        top_n: int,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Extract top N peaks based on predicted intensity for similarity calculation.

        Parameters
        ----------
        aligned_exp_intensity : np.ndarray
            Aligned experimental intensity vector.
        aligned_pred_intensity : np.ndarray
            Aligned predicted intensity vector.
        matched_indices : np.ndarray
            Matching index pairs, shape (N, 2).
        top_n : int
            Number of top peaks to extract.

        Returns
        -------
        tuple of (np.ndarray, np.ndarray, np.ndarray)
            - Top N experimental intensity vector
            - Top N predicted intensity vector
            - Top N matching index pairs, shape (top_n, 2)
        """
        num_peaks = min(top_n, len(aligned_pred_intensity))
        top_pred_indices = np.argsort(-aligned_pred_intensity)[:num_peaks]

        top_exp_intensity = aligned_exp_intensity[top_pred_indices]
        top_pred_intensity = aligned_pred_intensity[top_pred_indices]
        top_matched_indices = matched_indices[top_pred_indices]

        return top_exp_intensity, top_pred_intensity, top_matched_indices

    def _align_spectra(
        self,
        exp_mz: List[float],
        exp_intensity: List[float],
        pred_mz: List[float],
        pred_intensity: List[float],
        pred_annotation: Optional[List[str]] = None,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Align experimental and predicted spectra.

        This is a wrapper around _align_spectra_all_peaks and _get_top_peaks_vectors
        to maintain backward compatibility while using the improved algorithm.

        Parameters
        ----------
        exp_mz : list of float
            Experimental m/z values.
        exp_intensity : list of float
            Experimental intensity values.
        pred_mz : list of float
            Predicted m/z values.
        pred_intensity : list of float
            Predicted intensity values.
        pred_annotation : list of str, optional
            Predicted fragment annotations.

        Returns
        -------
        tuple of (np.ndarray, np.ndarray, np.ndarray)
            - Aligned experimental intensity vector
            - Predicted intensity vector
            - Matching index pairs as int array of shape (top_n, 2)

        Notes
        -----
        The method first aligns all peaks using _align_spectra_all_peaks, then
        extracts the top N peaks using _get_top_peaks_vectors for compatibility
        with existing code.
        """
        # First align all peaks
        all_exp_intensity, all_pred_intensity, all_matched_indices, additional_info = (
            self._align_spectra_all_peaks(
                exp_mz,
                exp_intensity,
                pred_mz,
                pred_intensity,
                pred_annotation,
            )
        )

        # Then get top N peaks for compatibility with existing code
        top_exp_intensity, top_pred_intensity, top_matched_indices = self._get_top_peaks_vectors(
            all_exp_intensity, all_pred_intensity, all_matched_indices, self.top_n
        )

        return top_exp_intensity, top_pred_intensity, top_matched_indices

    def _calculate_similarity_features(
        self, exp_vector: np.ndarray, pred_vector: np.ndarray
    ) -> Dict[str, float]:
        """
        Calculate all similarity features between experimental and predicted vectors.

        Uses a single numba-compiled function that computes all metrics in one
        pass, reusing shared intermediate values (L2 norms, sums, ranks).
        """
        (sa, cos, pear, spear, mse, ent, seen, not_seen) = compute_similarity_features(
            np.ascontiguousarray(exp_vector, dtype=np.float64),
            np.ascontiguousarray(pred_vector, dtype=np.float64),
        )
        return {
            "spectral_angle_similarity": sa,
            "cosine_similarity": cos,
            "pearson_correlation": pear,
            "spearman_correlation": spear,
            "mean_squared_error": mse,
            "unweighted_entropy_similarity": ent,
            "predicted_seen_nonzero": int(seen),
            "predicted_not_seen": int(not_seen),
        }

    def _generate_features(self) -> pd.DataFrame:
        """
        Generate spectral similarity features.

        Returns
        -------
        pd.DataFrame
            DataFrame containing generated features.
        """
        psm_df = self.df.copy()
        pred_spectra_df = self._predict_theoretical_spectra(
            processed_peptides=psm_df["processed_peptide"].tolist(),
            charges=psm_df["charge"].tolist(),
        )

        exp_spectra_df = self._extract_experimental_spectra()

        if exp_spectra_df.empty:
            raise ValueError("SpectralSimilarity could not extract experimental spectra.")

        psm_df = pd.merge(
            psm_df,
            exp_spectra_df,
            on=["scan", "mz_file_path", "charge"],
            how="inner",
            validate="m:1",
        )
        if len(psm_df) != len(self.df):
            raise ValueError(
                f"SpectralSimilarity expected {len(self.df)} PSM rows after matching "
                f"experimental spectra, but found {len(psm_df)}."
            )

        psm_df = pd.merge(psm_df, pred_spectra_df, on=["processed_peptide", "charge"], how="inner")
        if len(psm_df) != len(self.df):
            raise ValueError(
                f"SpectralSimilarity expected {len(self.df)} PSM rows after matching "
                f"predicted spectra, but found {len(psm_df)}."
            )

        n_rows = len(psm_df)
        logger.info(f"Matching experimental and predicted spectra for {n_rows} PSMs...")

        exp_mz_col = psm_df["mz"].values
        exp_int_col = psm_df["intensity"].values
        pred_mz_col = psm_df["pred_mz"].values
        pred_int_col = psm_df["pred_intensity"].values
        has_annotation = "annotation" in psm_df.columns
        pred_ann_col = psm_df["annotation"].values if has_annotation else None

        sa_arr = np.empty(n_rows, dtype=np.float64)
        cos_arr = np.empty(n_rows, dtype=np.float64)
        pear_arr = np.empty(n_rows, dtype=np.float64)
        spear_arr = np.empty(n_rows, dtype=np.float64)
        mse_arr = np.empty(n_rows, dtype=np.float64)
        ent_arr = np.empty(n_rows, dtype=np.float64)
        seen_arr = np.empty(n_rows, dtype=np.int64)
        not_seen_arr = np.empty(n_rows, dtype=np.int64)

        exp_vectors = [None] * n_rows
        pred_vectors = [None] * n_rows
        matched_indices_list = [None] * n_rows
        exp_top_vectors = [None] * n_rows
        pred_top_vectors = [None] * n_rows
        top_matched_list = [None] * n_rows
        exp_mz_sorted_list = [None] * n_rows
        exp_int_sorted_list = [None] * n_rows
        pred_mz_sorted_list = [None] * n_rows
        pred_int_sorted_list = [None] * n_rows
        pred_ann_sorted_list = [None] * n_rows if has_annotation else None

        for i in range(n_rows):
            pred_ann = pred_ann_col[i] if pred_ann_col is not None else None

            all_exp, all_pred, all_matched, info = self._align_spectra_all_peaks(
                exp_mz_col[i],
                exp_int_col[i],
                pred_mz_col[i],
                pred_int_col[i],
                pred_ann,
            )

            top_exp, top_pred, top_matched = self._get_top_peaks_vectors(
                all_exp,
                all_pred,
                all_matched,
                self.top_n,
            )

            (sa, cos, pear, spear, mse, ent, seen, not_seen) = compute_similarity_features(
                np.ascontiguousarray(top_exp, dtype=np.float64),
                np.ascontiguousarray(top_pred, dtype=np.float64),
            )
            sa_arr[i] = sa
            cos_arr[i] = cos
            pear_arr[i] = pear
            spear_arr[i] = spear
            mse_arr[i] = mse
            ent_arr[i] = ent
            seen_arr[i] = int(seen)
            not_seen_arr[i] = int(not_seen)

            exp_vectors[i] = all_exp
            pred_vectors[i] = all_pred
            matched_indices_list[i] = all_matched
            exp_top_vectors[i] = top_exp
            pred_top_vectors[i] = top_pred
            top_matched_list[i] = top_matched
            exp_mz_sorted_list[i] = info["exp_mz_sorted"]
            exp_int_sorted_list[i] = info["exp_intensity_sorted"]
            pred_mz_sorted_list[i] = info["pred_mz_sorted"]
            pred_int_sorted_list[i] = info["pred_intensity_sorted"]
            if pred_ann_sorted_list is not None:
                pred_ann_sorted_list[i] = info["pred_annotation_sorted"]

        psm_df = psm_df.reset_index(drop=True)
        psm_df["spectral_angle_similarity"] = sa_arr
        psm_df["cosine_similarity"] = cos_arr
        psm_df["pearson_correlation"] = pear_arr
        psm_df["spearman_correlation"] = spear_arr
        psm_df["mean_squared_error"] = mse_arr
        psm_df["unweighted_entropy_similarity"] = ent_arr
        psm_df["predicted_seen_nonzero"] = seen_arr
        psm_df["predicted_not_seen"] = not_seen_arr

        psm_df["exp_vector"] = exp_vectors
        psm_df["pred_vector"] = pred_vectors
        psm_df["matched_indices"] = matched_indices_list
        psm_df["exp_top_vector"] = exp_top_vectors
        psm_df["pred_top_vector"] = pred_top_vectors
        psm_df["top_matched_indices"] = top_matched_list
        psm_df["exp_mz_sorted"] = exp_mz_sorted_list
        psm_df["exp_intensity_sorted"] = exp_int_sorted_list
        psm_df["pred_mz_sorted"] = pred_mz_sorted_list
        psm_df["pred_intensity_sorted"] = pred_int_sorted_list
        if pred_ann_sorted_list is not None:
            psm_df["pred_annotation_sorted"] = pred_ann_sorted_list

        result_columns = [
            "mz_file_path",
            "spectrum_id",
            "scan",
            "peptide",
            "charge",
            "processed_peptide",
            "mz",
            "intensity",
            "pred_mz",
            "pred_intensity",
            "annotation",
            "exp_mz_sorted",
            "exp_intensity_sorted",
            "pred_mz_sorted",
            "pred_intensity_sorted",
            ("pred_annotation_sorted" if pred_ann_sorted_list is not None else None),
            "exp_vector",
            "pred_vector",
            "matched_indices",
            "exp_top_vector",
            "pred_top_vector",
            "top_matched_indices",
            "spectral_angle_similarity",
            "cosine_similarity",
            "pearson_correlation",
            "spearman_correlation",
            "mean_squared_error",
            "unweighted_entropy_similarity",
            "predicted_seen_nonzero",
            "predicted_not_seen",
        ]

        result_columns = [col for col in result_columns if col is not None]
        result_df = psm_df[result_columns]

        logger.info(
            f"Successfully generated spectral similarity features for {len(result_df)} PSMs"
        )
        return result_df

    def generate_features(self) -> pd.DataFrame:
        """
        Public interface for generating spectral similarity features.

        Returns
        -------
        pd.DataFrame
            DataFrame containing the generated features.

        Notes
        -----
        This method is a wrapper around _generate_features that ensures
        the results are cached and only computed once.
        """
        if self.results is None:
            self.results = self._generate_features()
        return self.results[self.id_column + self.feature_columns]

    def get_full_data(self) -> pd.DataFrame:
        """
        Return the full DataFrame with all columns.

        Returns
        -------
        pd.DataFrame
            Full DataFrame with all columns.

        Notes
        -----
        This method returns the complete DataFrame including all intermediate
        results and raw data used in feature generation.
        """
        return self.results

    @staticmethod
    def _resolve_mzml_paths(psms, params):
        """Return ``<mzmlDir>/<run>.mzML`` for each PSM.

        ``params`` must contain ``mzmlDir`` and each PSM must contain ``run``.
        """
        import os

        mzml_dir = params.get("mzmlDir", None)
        if mzml_dir is None:
            raise ValueError("mzmlDir is required for SpectralSimilarity feature generator.")
        mz_file_paths = [os.path.join(mzml_dir, f"{run}.mzML") for run in psms.df["run"]]
        for mz_file_path in set(mz_file_paths):
            if not os.path.exists(mz_file_path):
                logger.error(f"mzML file not found: {mz_file_path}")

        return mz_file_paths

    @classmethod
    def from_config(cls, psms, config, params):
        mz_file_paths = cls._resolve_mzml_paths(psms, params)
        mod_dict = config.get("modificationMap", None)
        if mod_dict == {}:
            mod_dict = None

        model_type = params.get("model", None)
        if model_type is None:
            raise ValueError("Model type is required for SpectralSimilarity feature generator.")

        n = len(psms)
        collision_energy = params.get("collisionEnergy", None)
        instrument = params.get("instrument", None)
        fragmentation_type = params.get("fragmentationType", None)

        return cls(
            spectrum_ids=psms.df["psm_id"].tolist(),
            peptides=[
                to_proforma(sequence, mods, sites)
                for sequence, mods, sites in zip(
                    psms.df["sequence"], psms.df["mods"], psms.df["mod_sites"]
                )
            ],
            charges=psms.df["charge"].tolist(),
            scan_ids=psms.df["scan"].tolist(),
            mz_file_paths=mz_file_paths,
            model_type=model_type,
            collision_energies=[collision_energy] * n if collision_energy else None,
            instruments=[instrument] * n if instrument else None,
            fragmentation_types=[fragmentation_type] * n if fragmentation_type else None,
            remove_pre_nxt_aa=config["removePreNxtAA"],
            mod_dict=mod_dict,
            url=params.get("url"),
            ssl=params.get("ssl", True),
            top_n=params.get("numTopPeaks", 36),
            tolerance_ppm=params.get("tolerance", 20),
        )

    def apply(self, psms):
        features = self.generate_features()
        features = features.rename(columns={"spectrum_id": "psm_id"})
        psms.add_features(
            features[["psm_id", *self.feature_columns]],
            on="psm_id",
            columns=self.feature_columns,
        )


feature_generator_factory.register_generator(
    "SpectralSimilarity", SpectralSimilarityFeatureGenerator
)
